name: SonarCloud analysis

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
 #   branches: [ "main" ]
 workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            -Dsonar.projectKey=SowmyaRahul_spring-petclinic
            -Dsonar.organization=sowmyarahul
           
          projectBaseDir: .
      - name: Set up JDK 
        uses: actions/setup-java@v4
        with:
         java-version: '11'
         distribution: 'adopt'
        
      - name: Build with Maven
        working-directory: ./
        run: |
           ls -l /home/runner/work/spring-petclinic/spring-petclinic/
           mvn -f pom.xml package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: petclinic
          path: target/petclinic.jar

      - name: Build and push Docker image to ECR
        env:
         ECR_REGISTRY: 637423519309.dkr.ecr.ap-southeast-2.amazonaws.com/1petclinic
         ECR_REPOSITORY: 1petclinic
         IMAGE_TAG: ${{ github.sha }}
        run: |
            
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

        
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
