name: SonarCloud analysis

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
 #   branches: [ "main" ]
 workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # - name: Analyze with SonarCloud
      #   uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      #   with:
      #     # Additional arguments for the SonarScanner CLI
      #     args:
      #       -Dsonar.projectKey=SowmyaRahul_spring-petclinic
      #       -Dsonar.organization=sowmyarahul
           
      #     projectBaseDir: .
          
      - uses: actions/checkout@v4
      
      
      - name: Set up JDK 
        uses: actions/setup-java@v4
        with:
         java-version: '17'
         distribution: 'adopt'
        
      - name: Build with Maven
        working-directory: .
        run: |
           pwd && ls -la
           mvn -f pom.xml package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-petclinic-3.3.0-SNAPSHOT.jar
          path: target

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-2  # Replace with your AWS region

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t petclinic:latest .
          docker tag petclinic:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/1petclinic:latest
        env:
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
           AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Push Docker image to ECR
        run: |
           docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/1petclinic:latest
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # - name: Build and push Docker image to ECR
      #   env:
      #    ECR_REGISTRY: 637423519309.dkr.ecr.ap-southeast-2.amazonaws.com/1petclinic
      #    ECR_REPOSITORY: 1petclinic
      #    IMAGE_TAG: ${{ github.sha }}
      #   run: |
            
      #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      #       aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

        
      #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
